### ISSUE TITLE
Question about the real size of checker board

### ISSUE THREAD

**Issue by Hanning-Liu** [jspark-noticekorea/Camera-calibration-opencvSharp4#1]
@jspark-noticekorea @moran991231
Hi, moran! Thanks for your wonderful work. I have downloaded and tried your code. 

I'm a little confused with the code snippet below, which is from file `Form1.cs` and `Line106-108` :
```c#
Point3f[] objp = new Point3f[NX * NY]; //Line106
for (int i = 0; i < NX * NY; i++) //Line107
      objp[i] = new Point3f((float)(i % NX), (float)(i / NX), 0.0f); //Line108
``` 

It seems that the code doesn't define the real size of Square in the checker board, and then strightly use it in `Line134` and `Line147`:
```c#
object_points.Add(objp); //Line134
``` 
```c#
double retval = Cv2.CalibrateCamera(object_points, image_points, img_size, mtx, dist, out _, out _); //Line147
``` 

I'm thinking about the calibration result might be wrong, or I miss something important in your code.
Could you please help me to figure out the problem?
Thank you!

**Comment by moran991231** [comment]
Hi @Hanning-Liu !  

I'm happy to receive a first question on this repo. (:  

Well, I ask you for reading the openCV document about camera calibration first. [OpenCV: Camera Calibration](https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html)  
You can find python codes there. Mine is based on that.  

![image](https://github.com/jspark-noticekorea/Camera-calibration-opencvSharp4/assets/55349869/b81dc7e0-d8fc-4e48-baae-c03089e20600)  
Cam you find the equal flow of code from the python code?  

When I run the python code...
```
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
```

Then I can get the object like below:
![image](https://github.com/jspark-noticekorea/Camera-calibration-opencvSharp4/assets/55349869/9f5bbb1f-9e56-4243-93c1-d6f85919ecad)

 The code `Form1.cs Line 106-108` also provide similar result with the python code.

I believe my response would be helpful. If you have questions more, please feel free to leave comments. (:

**Comment by Hanning-Liu** [comment]
Yes, I can get the same result as you said above.
I've also watched a video about ArucoMarker pose estimation: https://www.youtube.com/watch?v=mn-M6Qzx6SE&t=1s
The Python file looks similar as yours, but it has the `The size of Square in the checker board` part.:
```python
# Checker board size
CHESS_BOARD_DIM = (9, 6)

# The size of Square in the checker board.
SQUARE_SIZE = 20  # millimeters                                       This Line!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
calib_data_path = "../opencv/calib_data"
CHECK_DIR = os.path.isdir(calib_data_path)
if not CHECK_DIR:
    os.makedirs(calib_data_path)
    print(f'"{calib_data_path}" Directory is created')
else:
    print(f'"{calib_data_path}" Directory already Exists.')

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
obj_3D = np.zeros((CHESS_BOARD_DIM[0] * CHESS_BOARD_DIM[1], 3), np.float32)
obj_3D[:, :2] = np.mgrid[0 : CHESS_BOARD_DIM[0], 0 : CHESS_BOARD_DIM[1]].T.reshape(-1, 2)
obj_3D *= SQUARE_SIZE #                                              This Line!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
print(obj_3D)

# Arrays to store object points and image points from all the images.
#......
``` 
Perhaps the real size of the square on the checkerboard might not be essential when aiming for an undistorted image, but it becomes critical when estimating the marker's pose. (I'm not sure, I'm new to this.>_<)

**Comment by moran991231** [comment]
Hi @Hanning-Liu !
I'm not sure the reason why `SQUARE_SIZE` is multiplied. I don't know but, the actual size of checker board can be critical as you said...  
I found another OpenCV document: [Pose Estimation](https://docs.opencv.org/4.x/d7/d53/tutorial_py_pose.html).  
`SQUARE_SIZE` isn't multiplied too.  
Is there anything different between the result of `SQUARE_SIZE=1`  and `SQUARE_SIZE=20`, when the other conditions are same?

**Comment by Hanning-Liu** [comment]
Hi @moran991231!
I have tried to calibrate the camera using the code with 
version1: with `SQUARE_SIZE = 20` and `obj_3D *= SQUARE_SIZE`
version2: without `SQUARE_SIZE = 20` and `obj_3D *= SQUARE_SIZE`

And only the `tvecs` part is different like this:
![image](https://github.com/jspark-noticekorea/Camera-calibration-opencvSharp4/assets/42676581/f0bf6c2a-d404-4c8f-bc48-1fbac92dfbee)

And then I tried to estimate the pose of ArucoMarker, the results are also the same:
![6062bbec7876472db20be812b3ef094](https://github.com/jspark-noticekorea/Camera-calibration-opencvSharp4/assets/42676581/b5854d84-70d1-45ff-964a-2df7189c784f)
above version1
![a8177755ca12a3e68ceb14cf6ca4d1c](https://github.com/jspark-noticekorea/Camera-calibration-opencvSharp4/assets/42676581/6f653d9c-173c-4536-ac25-fd37a0df58dc)
above version2

I suppose there should be a big difference, but it seems there isn't.

**Comment by moran991231** [comment]
Hi @Hanning-Liu!  

Thanks for your kind reply!

`t_vectors1` is around 20 times of `t_vectors2`. The number 20 came from `SQUARE_SIZE`, I guess.   
In my opinion, `SQUARE_SIZE` affects the norm (size) of `t_vectors`, not the direction.  
I don't know what those vectors mean, but If you don't utilize the norm of `t_vectors` in your project, you can ignore the `SQUARE_SIZE` factors.  
By the way, the consideration regarding `SQUARE_SIZE` is great!  
I wish you to have a nice day!  :)

**Comment by Hanning-Liu** [comment]
Hi @moran991231!

Thank you for your nice work and patient reply too!

May your day be filled with joy and positivity! 😊
